version: '3.8'
services:
  jenkins:
    image: jenkins
    build: ./
    restart: always
    container_name: jenkins
    ports:
      - 8080:8080
    volumes:
      - jenkins:/var/jenkins_home
      - ./jenkins/jenkins.yml:/var/jenkins_home/jenkins.yml
    secrets:
      - agent_private_key

    environment:
      CASC_JENKINS_CONFIG: '/var/jenkins_home/jenkins.yml'
      JENKINS_ADMIN_ID: ${JENKINS_ADMIN_ID}
      JENKINS_ADMIN_PASSWORD: ${JENKINS_ADMIN_PASSWORD}
      JENKINS_URL: ${JENKINS_URL}
      JENKINS_AGENT_HOST: ${JENKINS_AGENT_HOST}
    depends_on: 
      - agent
  agent:
    image: jenkins-mvn-agent
    build: 
      context: ./agents
      dockerfile: Dockerfile
    container_name: jenkins-mvn-agent
    privileged: true
    user: root
    ports:
      - 2222:22
    environment:
      JENKINS_AGENT_SSH_PUBKEY: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC71tVHIsfbqFC7yOo5jF8P/lUcIryS2hBg9RWSogGe2ylBOba95G1DLre1+LWh27VHMJbaWi65OyaNxEkWxOmnFKD6LG6c3JYDkw68LTsDXr5qt/Vjw8wE1oow0EG9XkglUwfubSSa1xZgP9DZB3SuZ+X8b4D97jhyuB+fBeTWYizaiDCBmS3ZKwwT4vdxVwKS/wgrisc+t6B1cF2GBCe8H5hOZbyK5ef0xAvh1ni4L37a0FuTObX3J1qyUDiyTRRlaFR4eeV5ZHp6e6LSnlY9NVv0odz16aCrYT0LL9HKkqHhQWU6FLpjPgim8b5GxNGguIcBY6+wRU6chLrmAB9zo9qROi+J+7Cp7vQv8T0YSfqNy9OjKvsuzJO8niWBLnmwX5pLGMS65zY4DxDk8NV9RdeQfiTTQKxObzH+sjzs9PQgdKAtosWlUrgz1ZfToJ28FdFgbNi07pieOsUH2y2DuuxlF/b9imEs3sh9xKZZviSvrNyoSgRvpkkOTjQygEk="

secrets:
  agent_private_key:
    file: ./ssh/id_rsa

volumes:
  jenkins: