Vagrant.configure("2") do |config|

  config.vm.define "jenkins" do |server|
    server.vm.box =  "hashicorp/bionic64"
    server.vm.hostname = "jenkins"
    server.vm.network "public_network", bridge: "BRIDGE"

    server.vm.provider "virtualbox" do |vb|
      vb.name = "jenkins-server"
      vb.memory = "1024"
      vb.cpus = "1"
    end

    server.vm.provision "shell", path: "scripts/docker.sh"
  end
 
end
